name: challenge2-auto

on:
  push:
    branches:
    - main
env:
  ARTIFACT_NAME: my-artifact

jobs:
  gen-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        uses: actions/checkout@v2.4.0
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "{{env.ARTIFACT_NAME}}"
          path: /home 
