name: challenge6-auto
on:
  push:
    branches:
      - main
    
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: check-python
        run: python hello.py
  job-2:
    runs-on: ubuntu-latest
    needs:
      - job-1
    steps:
      - uses: actions/checkout@v2
      - name: create artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: my-python
          path: ./hello.py
        
    
